A compact expression for the Legendre polynomials is given by ***Rodrigues'*** formula:

${\displaystyle P_{n}(x)={\frac {1}{2^{n}n!}}{\frac {d^{n}}{dx^{n}}}(x^{2}-1)^{n}\,.}$

This formula enables derivation of a large number of properties of the ${\displaystyle P_{n}}$'s. Among these are explicit representations such as

${\displaystyle {\begin{aligned}P_{n}(x)&={\frac {1}{2^{n}}}\sum _{k=0}^{n}{\binom {n}{k}}^{2}(x-1)^{n-k}(x+1)^{k},\\P_{n}(x)&=\sum _{k=0}^{n}{\binom {n}{k}}{\binom {n+k}{k}}\left({\frac {x-1}{2}}\right)^{k},\\P_{n}(x)&={\frac {1}{2^{n}}}\sum _{k=0}^{[{\frac {n}{2}}]}(-1)^{k}{\binom {n}{k}}{\binom {2n-2k}{n}}x^{n-2k},\end{aligned}}}$

The last formula is equivalent to the following:

<img src='assets/1.png'>

We will use the last one for python implementation

In [1]:
import numpy as np

In [2]:
def factorial(n):
    """
    Function to return the factorial of a number
    
    Parameters:
        n (int) - the number which factorial we want to calculate
        
    Returns:
        int - factorial
    """
    if n < 0:
        print('Factorial does not exist for negative numbers')
        return None
    elif n == 0:
        return 1
    
    if n == 1:
        return n
    else:
        return n*factorial(n-1)

In [3]:
def legendre_polynomials(n):
    """
    Function takes n as argument and implements Legendre n-th polynomial.
    
    Parameters:
        n (non-negative int) - for n-th legendre polinomeal
        
    Returns:
        list(coefficients of legendre polinomeal)
        
    Print:
        Print obtained legendre polinomeal
    """
    polynom = np.zeros([n+1])
    
    for k in range(int(n/2)+1):
        coef = (1/(2**n)) * ((-1)**k) * factorial(2*n - 2*k) / (factorial(k)*factorial(n-k)*factorial(n-2*k))
        polynom[n-2*k] = coef
        
    polynom_str = ''
    for i in range(len(polynom)):
        if polynom[i] != 0 and i == 0:
            polynom_str += str(polynom[i])
        
        elif polynom[i] != 0 and i == 1:
            if polynom[i] > 0 and polynom_str != "":
                polynom_str += (' +' + str(polynom[i]) + ' *X')
            else:
                polynom_str += (' ' + str(polynom[i]) + ' *X')
        
        elif polynom[i] != 0 and i != 0:
            if polynom[i] > 0 and polynom_str != "":
                polynom_str += (' +' + str(polynom[i]) + ' *X^' + str(i))
            else:
                polynom_str += (' ' + str(polynom[i]) + ' *X^' + str(i))
                
    print(polynom_str)
    
    return polynom

In [4]:
legendre_polynomials(0)

1.0


array([1.])

In [5]:
legendre_polynomials(1)

 1.0 *X


array([0., 1.])

In [6]:
legendre_polynomials(2)

-0.5 +1.5 *X^2


array([-0.5,  0. ,  1.5])

In [7]:
legendre_polynomials(3)

 -1.5 *X +2.5 *X^3


array([ 0. , -1.5,  0. ,  2.5])

In [8]:
legendre_polynomials(4)

0.375 -3.75 *X^2 +4.375 *X^4


array([ 0.375,  0.   , -3.75 ,  0.   ,  4.375])

In [9]:
legendre_polynomials(5)

 1.875 *X -8.75 *X^3 +7.875 *X^5


array([ 0.   ,  1.875,  0.   , -8.75 ,  0.   ,  7.875])

In [10]:
legendre_polynomials(50)

-0.11227517265921705 +143.15084514050173 *X^2 -30347.979169786366 *X^4 +2559346.243318651 *X^6 -114622149.61148526 *X^8 +3155929852.6362276 *X^10 -58336885154.79088 *X^12 +767354412420.7107 *X^14 -7481705521101.931 *X^16 +55697141101536.59 *X^18 -323629704084717.9 *X^20 +1492059025325647.2 *X^22 -5524943202473955.0 *X^24 +1.6574829607421866e+16 *X^26 -4.051625015147567e+16 *X^28 +8.093935949800542e+16 *X^30 -1.3217919595440402e+17 *X^32 +1.7600331439917968e+17 *X^34 -1.899718314149876e+17 *X^36 +1.6457019250601344e+17 *X^38 -1.1266728563873227e+17 *X^40 +5.953962249201299e+16 *X^42 -2.3413043939776776e+16 *X^44 +6447070070373315.0 *X^46 -1108804604301793.6 *X^48 +89609514959900.05 *X^50


array([-1.12275173e-01,  0.00000000e+00,  1.43150845e+02,  0.00000000e+00,
       -3.03479792e+04,  0.00000000e+00,  2.55934624e+06,  0.00000000e+00,
       -1.14622150e+08,  0.00000000e+00,  3.15592985e+09,  0.00000000e+00,
       -5.83368852e+10,  0.00000000e+00,  7.67354412e+11,  0.00000000e+00,
       -7.48170552e+12,  0.00000000e+00,  5.56971411e+13,  0.00000000e+00,
       -3.23629704e+14,  0.00000000e+00,  1.49205903e+15,  0.00000000e+00,
       -5.52494320e+15,  0.00000000e+00,  1.65748296e+16,  0.00000000e+00,
       -4.05162502e+16,  0.00000000e+00,  8.09393595e+16,  0.00000000e+00,
       -1.32179196e+17,  0.00000000e+00,  1.76003314e+17,  0.00000000e+00,
       -1.89971831e+17,  0.00000000e+00,  1.64570193e+17,  0.00000000e+00,
       -1.12667286e+17,  0.00000000e+00,  5.95396225e+16,  0.00000000e+00,
       -2.34130439e+16,  0.00000000e+00,  6.44707007e+15,  0.00000000e+00,
       -1.10880460e+15,  0.00000000e+00,  8.96095150e+13])