In [1]:
import numpy as np

In [10]:
# x  =np.random.rand(64)
x = np.zeros(64)

In [12]:
x[0] = 1

In [13]:
coef = np.fft.fft(x)

In [14]:
coef

array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j,
       1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j,
       1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j,
       1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j,
       1.+0.j, 1.-0.j, 1.-0.j, 1.-0.j, 1.-0.j, 1.-0.j, 1.-0.j, 1.-0.j,
       1.-0.j, 1.-0.j, 1.-0.j, 1.-0.j, 1.-0.j, 1.-0.j, 1.-0.j, 1.-0.j,
       1.-0.j, 1.-0.j, 1.-0.j, 1.-0.j, 1.-0.j, 1.-0.j, 1.-0.j, 1.-0.j,
       1.-0.j, 1.-0.j, 1.-0.j, 1.-0.j, 1.-0.j, 1.-0.j, 1.-0.j, 1.-0.j])

In [16]:
x = np.ones(64)

In [17]:
coef = np.fft.fft(x)

In [18]:
coef

array([64.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
        0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
        0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
        0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,
        0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.-0.j,  0.-0.j,
        0.-0.j,  0.-0.j,  0.-0.j,  0.-0.j,  0.-0.j,  0.-0.j,  0.-0.j,
        0.-0.j,  0.-0.j,  0.-0.j,  0.-0.j,  0.-0.j,  0.-0.j,  0.-0.j,
        0.-0.j,  0.-0.j,  0.-0.j,  0.-0.j,  0.-0.j,  0.-0.j,  0.-0.j,
        0.-0.j,  0.-0.j,  0.-0.j,  0.-0.j,  0.-0.j,  0.-0.j,  0.-0.j,
        0.-0.j])

In [19]:
x = np.random.rand(64)

In [20]:
coef = np.fft.fft(x)

In [21]:
rev_coef = np.fft.ifft(coef)

In [22]:
x

array([0.78809998, 0.30181405, 0.96384211, 0.17781561, 0.48830436,
       0.22047228, 0.56656533, 0.74768516, 0.01241286, 0.93101008,
       0.12892411, 0.98211574, 0.20049441, 0.61916761, 0.26883927,
       0.16827014, 0.46782163, 0.50846314, 0.18777414, 0.86312167,
       0.20372875, 0.31411293, 0.16075014, 0.98163878, 0.1345052 ,
       0.08571154, 0.9017869 , 0.88210766, 0.83885094, 0.26865245,
       0.66635595, 0.73123378, 0.99217042, 0.37069658, 0.12288281,
       0.40957742, 0.55502065, 0.49869393, 0.67066119, 0.79658413,
       0.48318054, 0.53579594, 0.8328192 , 0.35404824, 0.80732763,
       0.69878428, 0.29911577, 0.28531464, 0.36903782, 0.06622703,
       0.29078996, 0.30875243, 0.66519415, 0.65533812, 0.83409331,
       0.9054268 , 0.70705033, 0.42836051, 0.72884931, 0.29793797,
       0.87995268, 0.59376317, 0.42543097, 0.09297412])

In [23]:
rev_coef

array([0.78809998+0.00000000e+00j, 0.30181405-4.48466854e-17j,
       0.96384211+1.17477104e-19j, 0.17781561+4.62860586e-17j,
       0.48830436+0.00000000e+00j, 0.22047228+4.89161626e-17j,
       0.56656533-5.51862393e-19j, 0.74768516+1.69571264e-17j,
       0.01241286+6.04482195e-18j, 0.93101008+1.46688712e-18j,
       0.12892411+1.79664231e-17j, 0.98211574+2.90293807e-17j,
       0.20049441+2.42346743e-19j, 0.61916761-1.26867932e-17j,
       0.26883927+2.90957460e-18j, 0.16827014+3.90918263e-17j,
       0.46782163+0.00000000e+00j, 0.50846314+1.06644658e-17j,
       0.18777414-2.06992046e-17j, 0.86312167+4.62860586e-17j,
       0.20372875+0.00000000e+00j, 0.31411293-2.04727764e-17j,
       0.16075014-5.51862393e-19j, 0.98163878-4.54929187e-17j,
       0.1345052 -7.40215712e-18j, 0.08571154+3.52040372e-17j,
       0.9017869 +6.26250630e-18j, 0.88210766-3.98428886e-17j,
       0.83885094+8.02691980e-18j, 0.26865245-5.96110412e-18j,
       0.66635595-6.12652346e-18j, 0.73123378-1.9580365

In [25]:
np.abs(x - rev_coef)

array([0.00000000e+00, 1.19737951e-16, 1.11022365e-16, 7.22764632e-17,
       1.11022302e-16, 7.39883699e-17, 5.51862393e-19, 2.22691155e-16,
       1.11186742e-16, 1.11031993e-16, 5.83462104e-17, 2.23934168e-16,
       2.42346743e-19, 1.11744827e-16, 1.66558869e-16, 3.90918263e-17,
       0.00000000e+00, 1.11533325e-16, 2.23007317e-16, 2.26817561e-16,
       8.32667268e-17, 1.67787144e-16, 1.66534368e-16, 2.26657037e-16,
       1.11268790e-16, 1.43173404e-16, 6.26250630e-18, 2.25590918e-16,
       1.11312098e-16, 1.66640109e-16, 1.11191213e-16, 1.12735719e-16,
       0.00000000e+00, 2.22300556e-16, 1.11900934e-16, 5.62724644e-17,
       0.00000000e+00, 1.66663989e-16, 1.11023674e-16, 3.33241911e-16,
       6.04482195e-18, 1.11909549e-16, 4.32358954e-18, 2.24292828e-16,
       1.11022567e-16, 1.11070365e-16, 1.11140901e-16, 2.77579146e-16,
       1.11022302e-16, 8.39468798e-17, 1.12935418e-16, 1.11404910e-16,
       1.11022302e-16, 2.22164006e-16, 1.11023674e-16, 3.33089269e-16,
      